// vue-app/src/components/ProfileForm.vue
<template>
  <section class="profile-form">
    <h2>Profile Form</h2>
    <p>This Vue starter mirrors the shape of the legacy form without completing the migration.</p>
    <form class="fields">
      <label>
        <span>Display name</span>
        <input v-model="displayName" />
      </label>
      <label>
        <span>Bio</span>
        <textarea v-model="bio" />
      </label>
    </form>
  </section>
</template>

<script setup lang="ts">
import { useProfileForm } from "../composables/useProfileForm";

const { displayName, bio } = useProfileForm();
</script>

<style scoped>
.profile-form {
  display: grid;
  gap: 1rem;
  padding: 1rem;
  border: 1px solid #d4d4d8;
  border-radius: 1rem;
  background: #ffffff;
}

.fields {
  display: grid;
  gap: 0.75rem;
}

label {
  display: grid;
  gap: 0.25rem;
}
</style>

// legacy-react/src/components/ProfileForm.tsx
export default function ProfileForm() {
  return (
    <form className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <label className="grid gap-1 text-sm text-slate-700">
        <span className="font-medium">Display name</span>
        <input className="rounded-lg border border-slate-300 px-3 py-2" defaultValue="Taylor Rivers" />
      </label>
      <label className="grid gap-1 text-sm text-slate-700">
        <span className="font-medium">Bio</span>
        <textarea className="min-h-24 rounded-lg border border-slate-300 px-3 py-2" defaultValue="Legacy React starter form." />
      </label>
    </form>
  );
}
